### ISSUE TITLE
Codelist builder search returns 500 error with unexpected characters

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/opencodelists#2166]
When constructing a search that contains a `*` or a `%`, or ends with a `-`, then the user receives a 500 error.

The expected behaviour should be to show the banner saying `There are no results for "..."`. This appears for other search terms that are not found in the database.

```
IntegrityError at /builder/532297c2/search/
UNIQUE constraint failed: codelists_search.version_id, codelists_search.slug
```

```
2024-11-27T14:42:27.918036Z [error    ] Internal Server Error: /builder/532297c2/search/ [django.request] ip=127.0.0.1 request_id=7eb67c68-f8ff-44a8-ab02-23fdcece696b user_id=lucyb
Traceback (most recent call last):
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
codelists.models.Search.DoesNotExist: Search matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlean.dbapi2.IntegrityError: UNIQUE constraint failed: codelists_search.version_id, codelists_search.slug

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/builder/decorators.py", line 18, in wrapped_view
    rsp = view_fn(request, version, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/builder/decorators.py", line 36, in wrapped_view
    return view_fn(request, draft, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/builder/views.py", line 231, in new_search
    search = actions.create_search(draft=draft, term=term, code=code, codes=codes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/.pyenv/versions/3.12.1/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/builder/actions.py", line 26, in create_search
    search, new = draft.searches.get_or_create(term=term, code=code, slug=slug)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 812, in get_or_create
    return super(RelatedManager, self.db_manager(db)).get_or_create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucy/datalab/ebmdatalab/opencodelists/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: codelists_search.version_id, codelists_search.slug
```

**Comment by rw251** [comment]
Fixed by #2416
